(:docstring-markup-format :scriba
 :systems (:example)
 :documents ((:title "Example of Codex documentation for a Common Lisp library"
              :authors ("Alexander Artemenko")
              :output-format (:type :single-html ;; This does not work and creates multiple files anyway
                              :template :minima)
              :sources ("index.scr"
                        "pros-and-cons.scr"
                        "handwritten.scr"
                        "extending.scr"
                        "autogenerated.scr"
                        "conclusion.scr"))))
